<a href="https://colab.research.google.com/github/shalini2705/DataAnalysis/blob/main/DATAANALYSIS_IPYNB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#1D
arr = np.array([10, 20, 30, 40, 50])
print(np.sum(arr))#sum
print(np.min(arr))#minimun value
print(np.max(arr))#max value
print(np.sum(arr,axis=0))
print(np.mean(arr))
print(np.var(arr))
print(np.std(arr))
print(np.percentile(arr,80))
print(np.quantile(arr,0.80))
print(np.quantile(arr,1))
#percentile->percen->0-100
#quantile->proportion->0-1
print(np.argmax(arr))#gives index value of max digit
print(np.argmin(arr))#gives index value of min digit
arr=np.array([10,100,1000])
print(np.log10(arr))#logs
print(np.log2(arr))#logs
print(np.log(arr))
print(np.log(2))
print(np.log(5))
arr=np.array([10.25,20.675,30.3])#rounding of numbers
print(np.round(arr))
arr=np.array([10.765,20.334,30.908])
print(np.round(arr,2))#2 reflects the decimal 2nd value
print(np.floor(arr))#gives lower limit values and decimal point before values
print(np.ceil(arr))#ives upper limit values and next number
arr=np.array([-10,-5,0,-3,6,4,30])
print(np.abs(arr))#removes -ve and gives +ve values
arr = np.array([780, 450, 870, 300, 70])
print(np.sort(arr))#sorting
print(np.sort(arr)[::-1])#decending order
print(np.sort(arr)[::1])#aesending order
print(arr[::-1])#reverse





150
10
50
150
30.0
200.0
14.142135623730951
42.0
42.0
50
4
0
[1. 2. 3.]
[3.32192809 6.64385619 9.96578428]
[2.30258509 4.60517019 6.90775528]
0.6931471805599453
1.6094379124341003
[10. 21. 30.]
[10.76 20.33 30.91]
[10. 20. 30.]
[11. 21. 31.]
[10  5  0  3  6  4 30]
[ 70 300 450 780 870]
[870 780 450 300  70]
[ 70 300 450 780 870]
[ 70 300 870 450 780]


In [ ]:
#2d
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.sum(arr,axis=0))
print(np.mean(arr))
print(np.var(arr))
print(np.std(arr))
print(np.percentile(arr,80))
print(np.quantile(arr,1))
print(np.argmax(arr))
print(np.argmin(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.log(arr))

210
10
60
[50 70 90]
35.0
291.6666666666667
17.07825127659933
50.0
60
5
0
[[1.         1.30103    1.47712125]
 [1.60205999 1.69897    1.77815125]]
[[3.32192809 4.32192809 4.9068906 ]
 [5.32192809 5.64385619 5.9068906 ]]
[[2.30258509 2.99573227 3.40119738]
 [3.68887945 3.91202301 4.09434456]]


In [ ]:
import numpy as np
arr1 = np.array([10, 20, 30])
arr2 = np.array([40, 50, 60])
result = np.concatenate((arr1, arr2))
print(result) #concatenation it combines 2 arrays into 1 array and changes it into 1D
print(result.ndim)
arr1 = np.array([
[10, 20],
[30, 40] ])
arr2 = np.array([
[50, 60],
[70, 80]])
result = np.concatenate((arr1, arr2), axis=1) #2d horizontal concatenation
print(result)
print(result.ndim)
result = np.concatenate((arr1, arr2), axis=0) #2d vertical concatenation
print(result)
print(result.ndim)
arr1 = np.array([
[10, 20],
[30, 40] ])
arr2 = np.array([
[50, 60],
[70, 80]])
result = np.stack((arr1, arr2), axis=0)#stack changes dimension
print(result)
print(result.ndim)
result = np.stack((arr1, arr2), axis=1)
print(result)
print(result.ndim)
arr1 = np.array([10, 20, 30])
arr2 = np.array([40, 50, 60])
result = np.stack((arr1, arr2),axis=0)
print(result)
result = np.stack((arr1, arr2),axis=1)
print(result)
arr1 = np.array([10, 20, 30]) #1d
arr2 = np.array([40, 50, 60])
result = np.vstack((arr1, arr2))#vstack exception case (chnages 1d to 2d)
print(result)
print(result.ndim)
arr1 = np.array([ #2d
[10, 20],
[30, 40] ])
arr2 = np.array([
[50, 60],
[70, 80]])
result = np.vstack((arr1, arr2))
print(result)
print(result.ndim)
#3d
arr1 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
arr2 = np.array([
    [[11,22], [33, 44]],
    [[55,66], [77, 88]]
])
result=np.vstack((arr1,arr2))
print(result)
print(result.ndim)
#h stack
arr1 = np.array([10, 20, 30]) #1d
arr2 = np.array([40, 50, 60])
result = np.hstack((arr1, arr2))
print(result)
print(result.ndim)



[10 20 30 40 50 60]
1
[[10 20 50 60]
 [30 40 70 80]]
2
[[10 20]
 [30 40]
 [50 60]
 [70 80]]
2
[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]
3
[[[10 20]
  [50 60]]

 [[30 40]
  [70 80]]]
3
[[10 20 30]
 [40 50 60]]
[[10 40]
 [20 50]
 [30 60]]
[[10 20 30]
 [40 50 60]]
2
[[10 20]
 [30 40]
 [50 60]
 [70 80]]
2
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[11 22]
  [33 44]]

 [[55 66]
  [77 88]]]
3
[10 20 30 40 50 60]
1


In [ ]:
import numpy as np
arr=np.array([10,20,30,40,50,60])
result=np.split(arr,3)
print(result)
result=np.split(arr,2)
print(result)
result=np.split(arr,[2,4])
print(result)
result=np.split(arr,[0,3,4])
print(result)
result=np.split(arr,3)
print(result)
arr=np.array([[10,20],[30,40],[50,60],[70,80]])
arr=np.split(arr,2,axis=0)
print(result)

[array([10, 20]), array([30, 40]), array([50, 60])]
[array([10, 20, 30]), array([40, 50, 60])]
[array([10, 20]), array([30, 40]), array([50, 60])]
[array([], dtype=int64), array([10, 20, 30]), array([40]), array([50, 60])]
[array([10, 20]), array([30, 40]), array([50, 60])]
[array([10, 20]), array([30, 40]), array([50, 60])]


In [ ]:
import numpy as np
arr=np.array([[10,20,88],[30,40,77],[50,60,66],[70,80,55]])
arr=np.split(arr,3,axis=1)
print(result)
arr=np.split(arr,[1,3],axis=1)
print(result)

[array([10, 20]), array([30, 40]), array([50, 60])]
[array([10, 20]), array([30, 40]), array([50, 60])]
