<a href="https://colab.research.google.com/github/AizerCain/Data-Analysis/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NUMPY MODULE

In [ ]:
import numpy as np

#print(np.__version__)
num= np.array([10,20,30,40,50])
print(num)
#arr = np.array([[10,20,30], [40,50,60]])
#print(arr)
#arr1 = np.array([[10,20,30], [40,50,60], [70,80,90]])
#print(arr1)
#arr2 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]], [[13,14,15], [16,17,18]]])
#print(arr2)
#print(arr2.ndim)
#print(arr2.shape)
arr = np.arange(1,7) #used to generate one-dimensional arrays in a specified range
print(arr)
zeros_1d = np.zeros(5) #to create a 1Dimensional array with zeroes as values
print(zeros_1d)
zeros_2d = np.zeros((2,3)) #to create a 2Dimensional array with zeroes as values
zeros_3d = np.zeros((2,3,3)) #to create a 3Dimensional array with zeroes as values
ones_1d = np.ones(5) #to create a 1Dimensional array with ones as values, same syntax as zeroes method
'''full_1d = np.full(5,10) #to create an array with the first input value as the LENGTH and the 2nd input value as the VALUE
print(full_1d)
full_2d = np.full((2,3), 7)
full_3d = np.full((2,3,3), 7)
print(full_3d)'''
arr1 = arr.reshape(2,3) #to reshape an array into a 2d array with correct dimensions only
arr2 = arr.reshape(2,3,1) #to reshape an array into a 3d array with correct dimensions only

[10 20 30 40 50]
[1 2 3 4 5 6]
[0. 0. 0. 0. 0.]


In [ ]:
print(np.arange(10,55,5))
print(np.arange(2, 31, 2))
print(np.arange(1001,1021))
print(np.arange(50,1, -1))
roll_no = np.arange(101, 109)
#print(roll_no.shape, roll_no.ndim)
#print(roll_no.reshape(2,4))
#print(roll_no.reshape(4,2))
#print(roll_no.reshape(2,1,4))
#print(roll_no.reshape(4,1,2))


arr_2d = np.full((2,5),7)
arr_3d = np.full((2,1,5),7)
print( arr_2d,"\n", arr_3d)
print(np.zeros((3,3)))
print(np.ones((3,3)))

[10 15 20 25 30 35 40 45 50]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
[1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014
 1015 1016 1017 1018 1019 1020]
[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2]
[[7 7 7 7 7]
 [7 7 7 7 7]] 
 [[[7 7 7 7 7]]

 [[7 7 7 7 7]]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr = np.array([10.9, 20.9, 3.0, 1],dtype = "int") #used to create an array of a specified data type that explicitly converts values into the above said  datatype
print(arr)
print(arr.dtype)

[10 20  3  1]
int64


In [ ]:
import numpy as np
arr=np.eye(3)
print(arr)
arr=np.eye(4)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
import numpy as np
arr=np.random.random(5) #0-1 FLOAT VALUES
print(arr)
arr=np.random.random((2,3))#1D
print(arr)
arr=np.random.random((2,2,3))#2D
print(arr)
arr=np.random.uniform(10,50,5)
print(arr)
arr=np.random.uniform(10,50,(2,3))
print(arr)
arr=np.random.uniform(10,50,(2,2,3))
print(arr)
arr=np.random.randn(5)
print(arr)
print(arr.mean())
arr.std()
arr=np.random.randn(2,3)
print(arr)
print(arr.mean())
arr.std()
arr=np.random.randn(2,3,5)
print(arr)
print(arr.mean())
arr.std()
arr=np.array([10,20,30,40,50])
result=np.random.choice(arr)
print(result)
arr=np.array([10,20,30,40,50])
result=np.random.choice(arr,3)
print(result)
name=["shalu","chinnu","nirup"]
result=np.random.choice(name,2)
print(result)
arr=[10,20,30]
result=np.random.choice(arr,size=5,p=[0.2,0.5,0.3])
print(result)
arr=np.random.uniform(10,50,(2,3))  #used to freeze values
np.random.seed(10)
print(arr)
arr=np.random.random((2,3))
np.random.seed(4)
print(arr)
arr=np.random.randn(2,3)
np.random.seed(5)
print(arr)
arr=np.array([10,20,30,40,50])
np.random.shuffle(arr)
print(arr)

[0.3637369  0.979445   0.08982104 0.39673661 0.35413804]
[[0.486638   0.99082093 0.80828168]
 [0.64945888 0.81947279 0.24254041]]
[[[0.76437261 0.11090076 0.20415475]
  [0.11909536 0.87790307 0.52367529]]

 [[0.492136   0.7318711  0.01458075]
  [0.09336303 0.82655425 0.83349274]]]
[45.69644069 48.32054018 32.45348482 13.62194782 49.83955652]
[[29.0960688  37.3966243  43.73501056]
 [34.64499325 32.52750027 24.7264877 ]]
[[[37.63724789 42.64670719 47.02573955]
  [10.22940226 38.82238293 36.6823655 ]]

 [[17.99061624 37.86659718 33.0165483 ]
  [33.18885594 12.58027595 17.08984518]]]
[ 1.10626582 -1.6127783  -0.26487859 -0.21313737 -0.18430823]
-0.23376733570412603
[[ 0.42384392 -0.72306169 -0.04241936]
 [-0.90760603 -0.74412559 -0.15469471]]
-0.35801057468780945
[[[ 0.55846676 -1.52235639 -0.89264319  0.62412594 -0.80518352]
  [ 0.21228006  0.49235385  1.66745318 -1.90475993 -0.52030071]
  [-0.43239057  0.27836227  0.27090734 -0.91362123  0.35889997]]

 [[-0.53508396 -0.95499726  1.696880

In [ ]:
import numpy as np
arr=np.array([10,20,30,40,50])
np.random.shuffle(arr)
print(arr)
arr=np.array([10,20,30,40,50])
result=np.random.permutation(arr)
print("original:",arr)
print("permutation:",result)
arr=np.array([10,20,30,40,50])
np.random.randint(arr)
print(arr)


[40 20 30 50 10]
original: [10 20 30 40 50]
permutation: [20 10 30 40 50]
[10 20 30 40 50]


In [ ]:
import numpy as np
roll_numbers=np.array([101,102,103,104,105,106,107,108])
np.random.shuffle(roll_numbers)
print(roll_numbers)
emp=np.array(["ravi","priya","arun","kiran"])
np.random.shuffle(emp)
print(emp)
num=np.array([10,20,30,40,50])
result=np.random.permutation(num)
print("original:",num)
print("permutation:",result)
arr = np.arange(10,60,10)
print(arr)
print(np.zeros((3,3)))
print(np.zeros((2,3,4)))
print(np.ones(5))
print(np.ones((2,3)))
arr=np.eye(5)
print(arr)


[103 107 105 108 106 104 102 101]
['kiran' 'priya' 'ravi' 'arun']
original: [10 20 30 40 50]
permutation: [30 20 10 50 40]
[10 20 30 40 50]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
arr = np.linspace(0,10,3)
#arr = np.linspace((1,10,3), 50)
print(arr)
arr = np.arange(1,11).reshape(2,5,1)
result = arr.ravel() #used to reshape an array into a 1D array
print(result)
#r= arr.T #used to store the Transpose of an array
#print(r)
new_arr = arr.astype(float) #used to change the data type of an array
print(new_arr)
arr = np.array([10,20,30,40,50])
print(arr[-2:]) #to index an array of 1D
print(arr[1:4]) #to slice an array of 1D
arr[4] = 100
print(arr)
arr = np.arange(1,11).reshape(2,5)
print(arr)
print(arr[1,2]) #to index an array of 2D
print(arr[0,1:4]) #to slice an array of 2D
n = np.insert(arr,3,89) #to insert a value after the specified place in an array
n1= np.insert(arr,3,[100,300]) #to insert multiple values in an array at a specified location
print(n)
new_arr= np.delete(arr,2) #to delete a value in an array at a specified location, to delete multiple values pass (arr,[location in list]) inside the delete method
print(new_arr)

[ 0.  5. 10.]
[ 1  2  3  4  5  6  7  8  9 10]
[[[ 1.]
  [ 2.]
  [ 3.]
  [ 4.]
  [ 5.]]

 [[ 6.]
  [ 7.]
  [ 8.]
  [ 9.]
  [10.]]]
[40 50]
[20 30 40]
[ 10  20  30  40 100]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
8
[2 3 4]
[ 1  2  3 89  4  5  6  7  8  9 10]
[ 1  2  4  5  6  7  8  9 10]


In [ ]:
arr = np.linspace(0,100,10)
print(arr)
arr = np.linspace(1,50,15)
print(arr)
arr = np.array([10,20,30,40,50,60,70])
print(arr[0])
print(arr[-1])
print(arr[3])
#print(np.where(arr == 60)[0]) to print the location of a value in an array
print(arr[5])
arr = np.array([10,20,30,40,50,60,70,80])
print(arr[0:4])
print(arr[1:5])
print(arr[-3:])
print(arr[::2])
arr= np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr[1,1], arr[0,2], arr[2,0])
print(arr[1])
print(arr[0:3,2])
print(arr[0:2])
print(arr[0:3,1:3])
print(arr[0:2,1:3])
print(arr[1:3])

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
[ 1.   4.5  8.  11.5 15.  18.5 22.  25.5 29.  32.5 36.  39.5 43.  46.5
 50. ]
10
70
40
60
[10 20 30 40]
[20 30 40 50]
[60 70 80]
[10 30 50 70]
50 30 70
[40 50 60]
[30 60 90]
[[10 20 30]
 [40 50 60]]
[[20 30]
 [50 60]
 [80 90]]
[[20 30]
 [50 60]]
[[40 50 60]
 [70 80 90]]


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
file_path = '/content/sample_data/mnist_train_small.csv'
df = pd.read_csv(file_path)
print("Dataset loaded successfully!")
display(df.head())
display(df.tail())
print("\nDataset Shape:")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("\nColumn Names:")
print(df.columns.tolist())
print(df.dtypes)
df.info()
display(df.describe())
print("\nNull values in each column:")
display(df.isnull().sum())

print("\nTotal null values:")
print(df.isnull().sum().sum())
null_summary = pd.DataFrame({
    'Null Count': df.isnull().sum(),
    'Null Percentage': (df.isnull().sum() / len(df)) * 100
})

print("\nNull Value Summary:")
display(null_summary[null_summary['Null Count'] > 0])

plt.figure(figsize=(12, 6))
sns.heatmap(df.isnull(), cbar=False)
plt.title("Missing Values Heatmap")
plt.show()
numeric_columns = df.select_dtypes(include=np.number).columns

for col in numeric_columns:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].median())

print("\nNull values after numerical imputation:")
print(df.isnull().sum().sum())

categorical_columns = df.select_dtypes(include=['object', 'category']).columns
for col in categorical_columns:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].mode()[0])
print("\nNull values after categorical imputation:")
print(df.isnull().sum().sum())

duplicate_count = df.duplicated().sum()
print("\nNumber of duplicate rows:")
print(duplicate_count)

if duplicate_count > 0:
    print("\nDuplicate rows:")
    display(df[df.duplicated()])

df = df.drop_duplicates()
print("\nDuplicates after removal:")
print(df.duplicated().sum())

print("\nShape after removing duplicates:")
print(df.shape)

duplicate_columns = df.T.duplicated()
print("\nDuplicate columns:")
print(df.columns[duplicate_columns].tolist())

df = df.loc[:, ~df.T.duplicated()]
print("\nShape after removing duplicate columns:")
print(df.shape)

print("\nFinal data types:")
print(df.dtypes.value_counts())

print("\nFinal total null values:")
print(df.isnull().sum().sum())

print("\nFinal duplicate rows:")
print(df.duplicated().sum())

print("\nFinal dataset information:")
df.info()

print("\nFinal dataset shape:")
print(df.shape)

print("Total Missing Values:",df.isnull().sum().sum())
print("Total Duplicate Rows:", df.duplicated().sum())
print("Final Rows:", df.shape[0])
print("Final Columns:", df.shape[1])

cleaned_path = ('/content/sample_data/''mnist_train_small_cleaned.csv')
df.to_csv(cleaned_path,index=False)
print("\nCleaned dataset saved successfully!")
print("Path:", cleaned_path)

# Statistical Operations

In [ ]:
arr = np.array([10,20,30,40,50])
print(np.sum(arr)) #to print the sum of values in an array
print(np.mean(arr)) #calculates the mean of the array
print(np.max(arr)) #picks the highest value in the array
print(np.min(arr)) #picks the least value in the array
print(np.std(arr)) #calculates the Standard Deviation of the array
print(np.var(arr)) #calculates the variance of the array
print(np.median(arr)) #calculates the median of the array
print(np.percentile(arr,75)) #calculates the marks obtained based on the percentile value we passed and the array
print(np.quantile(arr,0.5)) #calculates the marks obtained based on the percentile value passed between 0-1 and on the array
print(np.argmax(arr)) #gives the position of the highest value in the array
print(np.argmin(arr)) #gives the position(0 to N-1) of the least value in the array
print(np.log10(arr)) #gives the base-10 logarithm value for every value in the array
print(np.log(arr)) #gives the base-e logarithm value for every value in the array
print(np.round(arr,2)) #prints the rounded values in the array with the int value deciding the no of decimal points it can round off to
print(np.ceil(arr)) #prints the rounded value but rounding it off to the higher value for every element in the array
print(np.floor(arr)) #prints the rounded value but rounding it off to the lower value for every element in the array
print(np.abs(arr)) #removes the negative values of in an array and prints the converted positives
print(np.sort(arr)) #prints the sorted array
print(np.sort(arr)[::-1]) #prints the sorted array but in backwards

150
30.0
50
10
14.142135623730951
200.0
30.0
40.0
30.0
4
0
[1.         1.30103    1.47712125 1.60205999 1.69897   ]
[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
[10 20 30 40 50]
[10 20 30 40 50]
[10 20 30 40 50]
[10 20 30 40 50]
[10 20 30 40 50]
[50 40 30 20 10]


In [ ]:
arr = np.array([10,20,30,40,50,60]).reshape(2,3)
print(np.sum(arr))
print(np.sum(arr,axis=1)) #to count the sum row wise, column wise: 'axis=0'
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))
print(np.var(arr))
print(np.median(arr))
print(np.percentile(arr, 100, axis = 0)) #calculates the marks obtained based on the based on the percentile value we passed and the array based on the axis
print(np.quantile(arr,0.5,axis=0))
print(np.argmax(arr)) #gives the position(0 to N-1) of the highest value in the array
print(np.argmin(arr)) #gives the position(0 to N-1) of the least value in the array
print(np.log10(arr)) #gives the base-10 logarithm value for every value in the array
print(np.log2(arr)) #gives the base-2 logarithm value for every value in the array
print(np.log(arr)) #gives the base-e logarithm value for every value in the array
print(np.round(arr)) #prints the rounded values in the array
print(np.ceil(arr)) #prints the rounded value but rounding it off to the higher value for every element in the array
print(np.floor(arr)) #prints the rounded value but rounding it off to the lower value for every element in the array
print(np.abs(arr)) #removes the negative values of in an array and prints the converted positives
print(np.sort(arr)[::-1])

210
[ 60 150]
35.0
60
10
17.07825127659933
291.6666666666667
35.0
[40. 50. 60.]
[25. 35. 45.]
5
0
[[1.         1.30103    1.47712125]
 [1.60205999 1.69897    1.77815125]]
[[3.32192809 4.32192809 4.9068906 ]
 [5.32192809 5.64385619 5.9068906 ]]
[[2.30258509 2.99573227 3.40119738]
 [3.68887945 3.91202301 4.09434456]]
[[10 20 30]
 [40 50 60]]
[[10 20 30]
 [40 50 60]]
[[10 20 30]
 [40 50 60]]
[[10 20 30]
 [40 50 60]]
[[40 50 60]
 [10 20 30]]


In [ ]:
import numpy as np
#Question 1
arr = np.array([10, 20, 30, 40, 50])
print("1. Sum:", np.sum(arr))

#Question 2
marks = np.array([45, 78, 92, 56, 88, 67, 34])
print("2. Minimum:", np.min(marks))
print("   Maximum:", np.max(marks))

#Question 3
sales = np.array([12000, 15000, 18000, 11000, 20000])
print("3. Average Sales:", np.mean(sales))

#Question 4
data = np.array([10, 20, 30, 40, 50])
print("4. Variance:", np.var(data))

#Question 5
marks = np.array([60, 70, 80, 90, 100])
print("5. Standard Deviation:", np.std(marks))

#Question 6
marks = np.array([35, 42, 55, 60, 68, 72, 80, 85, 95, 100])
print("50th Percentile:", np.percentile(marks, 50))

#Question 7
salary = np.array([25000, 30000, 35000, 40000, 45000, 50000])
print("7. 25th Percentile:", np.quantile(salary, 0.25))
print("   75th Percentile:", np.quantile(salary, 0.75))

#Question 8
sales = np.array([15000, 22000, 18000, 35000, 27000, 12000])
print("8. Index of Highest Sales:", np.argmax(sales))


# 9. Index of lowest temperature
temperatures = np.array([32, 28, 35, 25, 30, 22, 38])
print("9. Index of Lowest Temperature:", np.argmin(temperatures))


# 10. Base-10 logarithm
arr = np.array([1, 10, 100, 1000, 10000])
print("10. Base-10 Logarithm:", np.log10(arr))


# 11. Base-2 logarithm
arr = np.array([1, 2, 4, 8, 16, 32])
print("11. Base-2 Logarithm:", np.log2(arr))


# 12. Natural logarithm
arr = np.array([1, 2, 3, 4, 5])
print("12. Natural Logarithm:", np.log(arr))


# 13. Square root
arr = np.array([4, 9, 16, 25, 36, 49])
print("13. Square Root:", np.sqrt(arr))


# 14. Round to nearest integer
prices = np.array([12.45, 23.67, 45.89, 56.12, 78.95])
print("14. Rounded Values:", np.round(prices))


# 15. Floor values
arr = np.array([10.2, 15.8, 20.4, 25.9, 30.1])
print("15. Floor Values:", np.floor(arr))


#Question 16
arr = np.array([10.2, 15.8, 20.4, 25.9, 30.1])
print("16. Ceiling Values:", np.ceil(arr))


#Question 17
profit = np.array([-5000, 3000, -2500, 4500, -1000])
print("17. Absolute Values:", np.abs(profit))


#Question 18
arr = np.array([45, 12, 89, 34, 67, 23])
print("18. Sorted Integer Array:", np.sort(arr))


#Question 19
names = np.array(["Ravi", "Anu", "Kiran", "Bala", "Meena"])
print("19. Sorted Names:", np.sort(names))

#Question 20
marks = np.array([78, 45, 92, 66, 88, 54, 99])
sorted_marks = np.sort(marks)
print("20. Decreasing Order:", sorted_marks[::-1])

In [ ]:
import numpy as np
marks = np.array([78, 65, 92, 56, 88, 71, 45, 83])
print(np.sum(marks))
salary = np.array([35000, 42000, 28000, 55000, 48000, 62000, 39000])
print(np.max(salary), np.min(salary))
sales = np.array([12500, 15000, 18000, 11000, 20000, 17500, 14000])
print(np.mean(sales))
marks = np.array([45, 50, 55, 60, 65, 70, 75, 80, 85, 90])
print(np.std(marks))
delivery = np.array([20, 22, 25, 28, 30, 35, 40])
print(np.std(delivery))
salary = np.array([25000, 30000, 35000, 40000, 45000, 50000, 55000, 60000, 65000, 70000])
print(np.percentile(salary,25))

578
62000 28000
15428.57142857143
14.361406616345072
6.5869382190848595
36250.0


In [ ]:
arr1= np.array([10,20,30])
arr2= np.array([40,50,60])
result = np.concatenate((arr1,arr2)) #used to join 2 or more arrays wihtout changing the dimensions of the array
#print(result)
#print(result.ndim)
result= np.stack((arr1,arr2)) #used to join 2 or more arrays with changing the dimensions of the combined array
#print(result)
arr1 = np.array([[10, 20],[30, 40]])
arr2 = np.array([[50, 60],[70, 80]])
result = np.concatenate((arr1, arr2), axis=1) #used to join 2 or more arrays column wise, by including axis=1 command
result1 = np.concatenate((arr1,arr2), axis=0) #used to join 2 or more arrays row wise, by including axis=0 command
#print(result)
arr1 = np.array([10, 20, 30])
arr2 = np.array([40, 50, 60])
result = np.stack((arr1, arr2), axis=0)
print(result)
result = np.stack((arr1, arr2), axis=1)
print(result)
arr1 = np.array([[1, 2],[3, 4]])
arr2 = np.array([[5, 6],[7, 8]])
result = np.stack((arr1, arr2), axis=0)
print(result,result.ndim)
result = np.stack((arr1, arr2), axis=1)
print(result,result.shape)
arr1 = np.array([[10, 20],[30, 40]])
arr2 = np.array([[50, 60],[70, 80]])
result = np.vstack((arr1,arr2))
result1 = np.hstack((arr1,arr2))
print(result)
print(result1)

[[10 20 30]
 [40 50 60]]
[[10 40]
 [20 50]
 [30 60]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 3
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]] (2, 2, 2)
[[10 20]
 [30 40]
 [50 60]
 [70 80]]
[[10 20 50 60]
 [30 40 70 80]]


In [ ]:
# 1
a = np.array([10, 20, 30])
b = np.array([40, 50, 60])
print(np.concatenate((a, b)))

# 2
maths = np.array([85, 90, 78])
science = np.array([88, 92, 80])
english = np.array([75, 85, 89])
print(np.concatenate((maths, science, english)))

# 3
student_id = np.array([[101], [102], [103]])
marks = np.array([[85], [90], [78]])
print(np.concatenate((student_id, marks), axis=1))

# 4
class_A = np.array([[101, 85], [102, 90], [103, 78]])
class_B = np.array([[104, 88], [105, 92], [106, 81]])
print(np.concatenate((class_A, class_B), axis=0))

# 5
names = np.array(["Ravi", "Anu", "Kiran", "Bala"]).reshape(-1, 1)
salary = np.array([45000, 55000, 65000, 75000]).reshape(-1, 1)
print(np.concatenate((names, salary), axis=1))

# 6
january = np.array([[101, 12000], [102, 15000], [103, 18000]])
february = np.array([[104, 14000], [105, 17000], [106, 20000]])
print(np.concatenate((january, february), axis=0))

# 7
north = np.array([100, 200, 300])
south = np.array([150, 250, 350])
east = np.array([120, 220, 320])
print(np.vstack((north, south, east)))

# 8
employee_id = np.array([101, 102, 103, 104])
salary = np.array([45000, 55000, 65000, 75000])
print(np.hstack((employee_id, salary)))

# 9
store1 = np.array([[101, 10], [102, 20]])
store2 = np.array([[103, 30], [104, 40]])
store3 = np.array([[105, 50], [106, 60]])
print(np.vstack((store1, store2, store3)))

# 10
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(np.concatenate((a, b), axis=1))
print(np.concatenate((a, b), axis=0))
print(np.vstack((a, b)))
print(np.hstack((a, b)))

[10 20 30 40 50 60]
[85 90 78 88 92 80 75 85 89]
[[101  85]
 [102  90]
 [103  78]]
[[101  85]
 [102  90]
 [103  78]
 [104  88]
 [105  92]
 [106  81]]
[['Ravi' '45000']
 ['Anu' '55000']
 ['Kiran' '65000']
 ['Bala' '75000']]
[[  101 12000]
 [  102 15000]
 [  103 18000]
 [  104 14000]
 [  105 17000]
 [  106 20000]]
[[100 200 300]
 [150 250 350]
 [120 220 320]]
[  101   102   103   104 45000 55000 65000 75000]
[[101  10]
 [102  20]
 [103  30]
 [104  40]
 [105  50]
 [106  60]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
result = np.split(arr,3) #Used to split arrays in equal parts specified
print(result)
result1 = np.split(arr, [1,3,5]) #used to split arrays in a customised way based on the poitions passed.
print(result1)
arr = np.array([[10,20],[30,40],[50,60],[70,80]])
result = np.split(arr, 2,axis=0)
print(result)
result1 = np.split(arr, 2,axis=1)
print(result1)
result1 = np.split(arr, [1,3,5], axis =0)
print(result1)

[array([10, 20]), array([30, 40]), array([50, 60])]
[array([10]), array([20, 30]), array([40, 50]), array([60])]
[array([[10, 20],
       [30, 40]]), array([[50, 60],
       [70, 80]])]
[array([[10],
       [30],
       [50],
       [70]]), array([[20],
       [40],
       [60],
       [80]])]
[array([[10, 20]]), array([[30, 40],
       [50, 60]]), array([[70, 80]]), array([], shape=(0, 2), dtype=int64)]
